apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-trade-platform
  namespace: ai-trade-platform
  labels:
    app: ai-trade-platform
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-trade-platform
  template:
    metadata:
      labels:
        app: ai-trade-platform
        version: v1
    spec:
      containers:
      - name: ai-trade-platform
        image: ai-trade-platform:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        # Load from ConfigMap
        - name: ACTIVE_AI_ENGINE
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: ACTIVE_AI_ENGINE
        - name: GROQ_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: GROQ_BASE_URL
        - name: GROQ_MODEL
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: GROQ_MODEL
        - name: OLLAMA_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: OLLAMA_BASE_URL
        - name: OLLAMA_MODEL
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: OLLAMA_MODEL
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: SPRING_PROFILES_ACTIVE
        - name: LOGGING_LEVEL_COM_EXAMPLE_AITRADE
          valueFrom:
            configMapKeyRef:
              name: ai-trade-platform-config
              key: LOGGING_LEVEL_COM_EXAMPLE_AITRADE
        
        # Load from Secret
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-trade-platform-secrets
              key: groq-api-key
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: ai-trade-platform-secrets
              key: database-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: ai-trade-platform-secrets
              key: database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-trade-platform-secrets
              key: database-password
        
        # Resource limits
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      
      # Restart policy
      restartPolicy: Always