apiVersion: v1
kind: Secret
metadata:
  name: ai-trade-platform-secrets
  namespace: ai-trade-platform
type: Opaque
stringData:
  # Groq API Key (replace with your actual key)
  groq-api-key: "YOUR_GROQ_API_KEY_HERE"
  
  # Database credentials (if using external DB)
  database-url: "jdbc:h2:mem:testdb"
  database-username: "sa"
  database-password: ""